### PR TITLE
chore(devex): fix settings.json

### PR DESCRIPTION
**Pull request by portenez**
**Describe your changes**
Rename settings.jsonc to settings.json

**Testing performed**
Made sure vscode picks up the changes. 

**Additional context**
Vscode requieres this particular extension

### CODE REVIEW

**Review by Abhilasha3112 — DISMISSED** [review]

**Comment by dakotalillie** [comment]
Should we remove the comment on line 8 then? JSON doesn't support comments

**Comment by portenez** [comment]
> Should we remove the comment on line 8 then? JSON doesn't support comments

We can, but we don't need to. `vscode` is sneaky and really doesn't follow the real `json` standard. It supports trailing comas, comments, and other things. what should we do? 

I'm good with either.

**Review by dakotalillie — DISMISSED** [review]
I'd personally favor removing it, so as not to trip up people or processes (such as GitHub's syntax highlighting) over VSCode's support for non-standard JSON. But I'll leave it up to you.

**Comment by portenez** [comment]
Closing this one in favor of:
https://github.com/bloomberg/coffeechat/pull/5

**Pull request closed without merging**
